### ISSUE TITLE
Angular 6

### ISSUE THREAD

**Issue by ghost** [LucHariman/ng-tagcanvas#1]
Hello,
I'm currently using angular 6 , downloaded ng-tagcanvas yesterday and added ng-tagcanvas.js into angular-cli.

I used <tag-canvas [tags]="myTags" [options]="{ dragControl: true, weight: true }" (tagClick)="showTagDetails($event)"></tag-canvas> in my components but nothing came out, would like to check with you how do I use it?

**Comment by LucHariman** [comment]
Hello @GoodJeans ,

There's an important step I forgot to put in the README (will add it asap):

After installing ng-tagcanvas through npm, import it under your app module.

```ts
import { TagCanvasModule } from 'ng-tagcanvas';
...
@NgModule({
...
  imports: [
...
    TagCanvasModule
  ]
...
```
An example is available here: https://github.com/LucHariman/ng-tagcanvas-example/blob/master/src/app/app.module.ts

Hope it helps.
