### ISSUE TITLE
error on Angular 10 : tag-canvas is not a know element

### ISSUE THREAD

**Issue by lorenzochaudessolle** [LucHariman/ng-tagcanvas#5]
Hello,

I'm using your tag-canvas component on Angular 10 and i can't build because i have this error when i put the html line in the code : 

`<tag-canvas [tags]="tags" [options]="options" (tagClick)="tagClicked($event)"></tag-canvas>`

**"'tag-canvas' is not a known element:
If 'tag-canvas' is an Angular component, then verify that it is part of this module."**

I thinks the issue is linked with the new version of Angular, can you help me to resolve it ?

Thanks a lot :) !

**Comment by LucHariman** [comment]
Hi @lorenzochaudessolle 

Verify if you have imported TagCanvasModule in one of your modules or, usually, on AppModule.

An example is available here: https://github.com/LucHariman/ng-tagcanvas-example/blob/master/src/app/app.module.ts#L13

**Comment by lorenzochaudessolle** [comment]
Hi @LucHariman, thanks for your fast reactivity. I haven't more this problem but another appeared.

I use Angular SSR (with prerendering) and when i built my app, the error was : 

  **document is not defined**.

So I've needed to change **my server.ts** file to implement this next code : 

    // ssr DOM 
    const domino = require('domino');
    const fs = require('fs');
    const path = require('path');
    // index from browser build!
    const template = fs.readFileSync(path.join(DIST_FOLDER, 'index.html')).toString();
    // for mock global window by domino
    const win = domino.createWindow(template);
    // mock
    global['window'] = win;
    // not implemented property and functions
    Object.defineProperty(win.document.body.style, 'transform', {
      value: () => {
       return {
          enumerable: true,
          configurable: true,
        };
      },
    });

    // mock documnet
    global['document'] = win.document;
    // othres mock
    global['CSS'] = null;
    // global['XMLHttpRequest'] = require('xmlhttprequest').XMLHttpRequest;
    global['Prism'] = null; 

Now it's run perfectly but i thinks i needed to do that because the component was made with an old version (Angular 6)

**Comment by LucHariman** [comment]
Thanks a lot for having shared your solution.

Yes indeed ng-tagcanvas has been built with an old version of Angular. I'm planning to rebuild the library as more users would like to use it on recent Angular versions.

**Comment by lorenzochaudessolle** [comment]
Not a prob !

I'm waiting for the new version ;) 
Anyway, good work for the component.
