### ISSUE TITLE
No image mode

### ISSUE THREAD

**Issue by nitinchotia2014** [LucHariman/ng-tagcanvas#6]
I found in your example that there is no image mode present through which we can show both image and text together. Is there a possibility of doing that with the current implementation?

**Comment by LucHariman** [comment]
Unfortunately it is not possible with the current version.

I didn't have time yet to get back into improving this library although there are some pending todos, but feel free to open a PR or fork the repository.

There's also a fork project that could interest you: https://github.com/rickithadi/cloudee

**Comment by LucHariman** [comment]
It is now possible in the version 1.0.0-alpha.

Note that there are breaking changes in this version, see in the [README.md](https://github.com/LucHariman/ng-tagcanvas#changes-compared-to-the-version-0x) file.
