### ISSUE TITLE
Support for Angular 18

### ISSUE THREAD

**Issue by akashkriplani** [LucHariman/ng-tagcanvas#7]
The package only supports till Angular 17. Are we considering updating the application to Angular 18?

**Comment by akashkriplani** [comment]
Pr has been raised for it - https://github.com/LucHariman/ng-tagcanvas/pull/8

**Comment by LucHariman** [comment]
Hi @akashkriplani , sorry for the late reply, and thx for the PR :slightly_smiling_face:.

**Comment by LucHariman** [comment]
Fixed on version [1.0.2](https://github.com/LucHariman/ng-tagcanvas/tree/1.0.2).
